### ISSUE TITLE
Logic js - refactoring

### ISSUE THREAD

**Issue by helenzhou6** [fac-13/PLHH-ToDo#16]
- Removing console.log from merge
- .concat() for sortToDo to prevent global variables being changed
- Remove the return [] in the remove function
- Remove cloning from delete todo and mark to do (as using map and filter that don't mutate original array)
- Tidy up
- Have a test case for all functions: for all of them ensure there is a test to make sure there is no mutating of global variables (using deepEquals?)

**Comment by haydnba** [comment]
console.logs are removed
see issue #18 for comments on the sort function mutability tests
tidying done
mutation tests written for the other functions
we did not remove cloning as the map function WAS mutating state
removed the empty array branch from delete function
