### ISSUE TITLE
Sort Function Mutability Test Function

### ISSUE THREAD

**Issue by haydnba** [fac-13/PLHH-ToDo#18]
Parissa has noticed a serious problem with testing for whether the sort function mutates its input array: what if the input array is already sorted? This makes the test quite problematic and since we can just avoid this problem by cloning the input array prior to sorting - we have decided to leave this as a stretch goal...

🏹

**Comment by helenzhou6** [comment]
Good point! 👍

**Comment by helenzhou6** [comment]
(I.e. Have a test case for all functions: for all of them ensure there is a test to make sure there is no mutating of global variables (using deepEquals?))
