### ISSUE TITLE
<label>

### ISSUE THREAD

**Issue by Parissai** [fac-13/PLHH-ToDo#28]
https://github.com/fac-13/PLHH-ToDo/blob/cce62a2db111cf7b29b77c1c3fc2c42512c3c231/index.html#L13

form element needs associating label

**Comment by helenzhou6** [comment]
Could be linked to #24 - when styling, the label could contain a ```h1``` tag

**Comment by Parissai** [comment]
A <label> can be associated with a control either by placing the control element inside the <label> element, or by using the for attribute. Such a control is called the labeled control of the label element. @haydnba @LawEKS
