### ISSUE TITLE
Good work on writing tests

### ISSUE THREAD

**Issue by trc5019** [fac-13/PLHH-ToDo#50]
<img width="568" alt="screen shot 2018-03-09 at 10 16 53" src="https://user-images.githubusercontent.com/29644807/37202698-1fc9818c-2383-11e8-9995-d75c9ccd5071.png">
<img width="127" alt="screen shot 2018-03-09 at 10 18 34" src="https://user-images.githubusercontent.com/29644807/37202731-3d577eac-2383-11e8-9607-fc2cb10e5200.png">

I ran your tests and they all passed good work.

**Comment by ybird21** [comment]
Also would like to say I like that you created one example state `sortState` to use in all your tests rather than writing out the example to be tested each time!
